### PR TITLE
Exclude CocoaPods article.

### PR DESCRIPTION
**Pull request by vchimev**

### CODE REVIEW

**Comment by jasssonpet** [comment]
:+1:

**Comment by alastaircoote** [comment]
Hi, I'm trying to get a CocoaPods library working with my app - and I was following those instructions to no success. Were they removed because they don't work any more, or...?

**Comment by jlooper** [comment]
hi Alastair, I have been working with cocoapods as well, using this article: https://www.nativescript.org/blog/using-cocoapods-is-a-piece-of-cake-with-nativescript-1.3.0

You can definitely make them work, but some work better than others, in my opinion. It takes some experimentation to figure out which ones can be used. What are you trying to integrate?

**Comment by alastaircoote** [comment]
Hi Jen!

I'm trying to set up the `Google/CloudMessaging` pod, discussed [here](https://developers.google.com/cloud-messaging/ios/client).

I've made some progress - I found an error in the output from the build scripts:

    platforms/ios/Pods/Headers/Public/GGLInstanceID/GGLInstanceID.h:2:1: error: use of '@import' when modules are disabled
    @import Foundation;

So I'm now trying to fix that issue - it appears that ["Enable Modules" ](http://stackoverflow.com/a/18947634/470339) is disabled by default in {N} projects. I've enabled it but still no luck.

Also of note: the build scripts don't fail because of this - they continue to launch the emulator. Maybe a suggestion for the {N} folks to have it throw that error and stop - it took me a long time to find out what the problem might be!

**Comment by alastaircoote** [comment]
Ah. I just found this:

http://stackoverflow.com/questions/31691191/can-i-disable-modules-import-import-in-google-cloud-messaging-on-ios

Which suggests that my problem is with the library itself. Disappointing, though it does mean there is maybe nothing wrong on the {N} side!

**Comment by jlooper** [comment]
One issue I found is that you have to be careful what version of iOS is supported by the cocoapod. You can specify the pod version like this in the podfile: platform :ios, '8.0' but if you do that, make sure to align your Xcode project to that version as well.

**Pull request merged**
