### PR TITLE
Reducing redundancy and fixing minor issues

### PR DESCRIPTION
**Pull request by ikoevska**

### CODE REVIEW

**Comment by ikoevska** [comment]
Not really. Markdown lets you use just 1. inside numbered lists, taking care of the correct numbering in the output. You can see it for yourself by reviewing the output in the rich diff or rendered in GitHub.

**Comment by ivanbuhov** [comment]
Sure, but I think it would be better if the list items are numbered correctly in the raw version of the file, too, because markdown files are often being opened with a plain text editor. Also, this way they will be consistent with all the other articles in the repo. Furthermore, I am not sure if most of the markdown transforming tools (e.g. our html documentation generator) will respect the rule.

**Comment by ikoevska** [comment]
All Markdown transforming tools respect this as it is not github-specific but it's Markdown-specific. The ones get transformed to `<li>` elements inside an `<ol>` element and there is no numbering there - numbering is handled by the HTML rendering. However, I respect your concern for consistency and usage in plain text editors and will update the list to use 1.,2.,3. 

Keep in mind though, that this approach you have adopted for the runtime docs leaves too much room for error when creating and editing lists. Should you ever choose to insert a new item between existing items, you will have to go and manually edit the remainder of the list and there is always the possibility of losing track of your list and duplicating the number entries.

**Comment by ivanbuhov** [comment]
Sure, this nice markdown feature can be of our help. I think the question comes down to *correct appearance in plain text editors* vs *easier content maintenance*. I am not against both options as long as we keep ordered lists consistent through the entire repo/article.

**Pull request merged**
